### ISSUE TITLE
Allow TransformResult to return different type

### ISSUE THREAD

**Issue by MindHardt** [ImmediatePlatform/Immediate.Apis#76]
# Problem
`TransformResult` method now expects the return value to be the same as its parameter.

# Motivation
I am developing a blazor server + webapi project and want to be able to have code like this
```cs
private static async ValueTask<ErrorOr<Response>> HandleAsync(...)
internal static Results<Ok, NotFound> TransformResult(ErrorOr<Response> value) => value.AsResult();
```
So that I can easily handle errors in my blazor code and still have a good swagger generated.

**Comment by viceroypenguin** [comment]
Already works as expected; I just misread the code.
